# Generated by Django 4.1.2 on 2022-11-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
